# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 23:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('type_lease', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('photos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('num_beds', models.PositiveIntegerField()),
                ('num_baths', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('amenities', models.TextField()),
                ('description', models.TextField()),
                ('rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField()),
                ('photos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Building')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
