# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160902_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='type_lease',
        ),
        migrations.AddField(
            model_name='unit',
            name='type_lease',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
