# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Building'),
            preserve_default=False,
        ),
    ]
