# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_favorite_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Building'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Unit'),
        ),
    ]
