# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20160916_0019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('creator', 'unit'), ('creator', 'building')]),
        ),
    ]
