# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160916_0129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([]),
        ),
    ]
