# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160916_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='security_deposit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
