# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 01:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_neighborhood_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
