# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 00:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20161119_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
