# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20161119_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='contact_secondary_phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
