# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_key',
            field=models.UUIDField(null=True),
        ),
    ]
