# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161004_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
